# Vesper

background #101010
foreground #ffffff   # <- branco puro

selection_background #1e222a
selection_foreground #ffffff

cursor #ffffff
cursor_text_color #101010

# ANSI (mantido original)
color0  #101010
color1  #ff8080
color2  #99ffe4
color3  #ffc799
color4  #80b3ff
color5  #e6ccff
color6  #8cffcc
color7  #c5cdd9   # mantém o "white" suave interno

# Bright
color8  #6b7089
color9  #ff9999
color10 #b3fff0
color11 #ffd9b3
color12 #99c2ff
color13 #f0d9ff
color14 #b3ffe0
color15 #ffffff   # branco puro nos brights
