confirm_os_window_close 0
cursor_trail 1
cursor_shape beam
cursor_beam_thickness 4
cursor_stop_blinking_after 0
cursor_shape_unfocused unchanged
font_size 10
cursor_blink_interval 0.5
window_padding_width 25
font_family     JetBrainsMonoNerdFont
bold_font        auto
italic_font      auto
bold_italic_font auto
background_opacity 0.9
# background_blur 20
include current-theme.conf
window_title_format {title}

